### ISSUE TITLE
表記ゆれ

### ISSUE THREAD

**Issue by 173210** [kagucho/tsubonesystem2#3]
`kagutyo`を`kagucho`に置き換えるべき.

**Comment by yumetodo** [comment]
いっそtexlintでも仕掛けるか？

**Comment by 173210** [comment]
自然言語でその類はクソ面倒くさいのを知っている.

**Comment by yumetodo** [comment]
運用例
https://github.com/asciidwango/js-primer

**Comment by 173210** [comment]
* できるだけ依存を増やしたくない
* 緩めの設定ができるものが良い
* CIに組み込めるものが良い
* Antとの親和性

**Comment by 173210** [comment]
a770ebfaf32883a06bbd137081829b241cc6e7b3 で解決
